root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/server ./cmd/server"
bin = "./tmp/server"
full_bin = "./tmp/server"
delay = 500
include_ext = ["go", "env"]
exclude_dir = ["tmp", "vendor"]

[server]
port = 8083
